- name: Set up local environment
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  become_method: sudo
  tasks:

    # Disable Auto-adding of Network Printers
    - name: Disable Auto-adding of Network Printers
      service:
        name: cups-browsed
        state: stopped

    # Install GU Firewall
    - name: Install GU Firewall
      apt:
        name: gufw
        update_cache: yes

    # Install Development Packages
    - name: Install Development Packages
      apt:
        name: "{{ dev_packages }}"
        update_cache: yes
      vars:
        dev_packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg2
        - vim
        - dirmngr

    # Install OpenJDK
    - name: "Install OpenJDK {{ openjdk_version | default('11') }}"
      apt:
        name: openjdk-{{ openjdk_version | default('11') }}-jdk
        state: latest
        install_recommends: no
        update_cache: yes
    - name: Confirm java is installed
      shell: java --version
      register: java_result
      ignore_errors: yes
    - debug:
         var: java_result

    # Install Maven
    - name: Install Maven
      apt:
        name: maven
        state: latest
        install_recommends: no
        update_cache: yes
    - name: Confirm Maven is installed
      shell: mvn --version
      register: maven_result
      ignore_errors: yes
    - debug:
         var: maven_result
    
    # Install Kotlin
    - name: Install Kotlin
      snap:
        name: kotlin
        classic: yes  
    - name: Confirm Kotlin is installed
      shell: kotlinc -version
      register: kotlin_result
      ignore_errors: yes
    - debug:
         var: kotlin_result
    
    # Install Go
    - name: Install Go
      apt:
        name: golang
        state: latest
        update_cache: yes
    - name: Confirm Go is installed
      shell: go version
      register: go_result
      ignore_errors: yes
    - debug:
         var: go_result
    
    # Install Docker
    - name: Create directory for apt repository keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        recurse: yes
    - name: Add Docker apt repository key.
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
    - name: Add apt repository for stable version of Docker
      apt_repository:
        repo: >
          deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] 
          https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present
        update_cache: yes
    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
    - name: Confirm Docker is installed
      shell: docker version
      register: docker_result
      ignore_errors: yes
    - debug:
         var: docker_result 
      
    # Install Docker-Compose
    - name: Install Docker-Compose
      apt:
        name: docker-compose
        update_cache: yes
    - name: Confirm Docker-Compose is installed
      shell: docker-compose --version
      register: docker_compose_result
      ignore_errors: yes
    - debug:
         var: docker_compose_result    
        
    # Install .NET Core SDK
    - name: Download MS product repository for .NET Core
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
      check_mode: no
      register: result
      retries: 3
      until: result is success
    - name: Install MS product repository for .NET Core installation
      apt: deb=/tmp/packages-microsoft-prod.deb
      check_mode: no
    - name: Install .NET Core SDK
      apt:
        name: dotnet-sdk-{{ dotnet_version | default('6.0') }}
        state: present
        update_cache: yes
    - name: Confirm .NET Core SDK is installed
      shell: dotnet --version
      register: dotnet_result
      ignore_errors: yes
    - debug:
         var: dotnet_result
    - name: Install ASP .NET Core Runtime
      apt:
        name: aspnetcore-runtime-{{ dotnet_version | default('6.0') }}
        update_cache: yes

    # Install Python
    - name: Install Python development environment packages
      apt:
        name: "{{ python_packages }}"
        update_cache: yes
      vars:
        python_packages:
        - python{{ python_version | default('3') }}-pip
        - build-essential
        - libssl-dev
        - libffi-dev
        - python{{ python_version | default('3') }}-dev
        - python{{ python_version | default('3') }}-venv

    # Install Node.JS
    - name: Install Node.js (JavaScript run-time environment)
      apt:
        name: nodejs
        update_cache: yes
    - name: Confirm NodeJS is installed
      shell: node --version
      register: node_result
      ignore_errors: yes
    - debug:
         var: node_result
 
    # Install NPM
    - name: Install NPM (Node Package Manager)
      apt:
        name: npm
        update_cache: yes      
    - name: Confirm NPM is installed
      shell: npm --version
      register: npm_result
      ignore_errors: yes
    - debug:
         var: npm_result
         
    # Install Create React App
    - name: Install Create React App
      npm:
        name: create-react-app
        global: yes
        state: present
    - name: Confirm Create React App is installed
      shell: create-react-app --version
      register: react_result
      ignore_errors: yes
    - debug:
         var: react_result         

    # Install Angular CLI
    - name: Install Angular CLI
      npm:
        name: "@angular/cli"
        global: yes
        state: present
    - name: Confirm Angular CLI is installed
      shell: ng --version
      register: ng_result
      ignore_errors: yes
    - debug:
         var: ng_result

    # Install Kubectl
    - name: Install Google Cloud public signing key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
      check_mode: no
    - name: Add the Kubernetes apt repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
        state: present
        update_cache: yes
      check_mode: no
    - name: Install Kubectl
      apt:
        name: kubectl
        update_cache: yes
    - name: Confirm Kubectl is installed
      shell: kubectl version --client
      register: kubectl_result
      ignore_errors: yes
    - debug:
         var: kubectl_result

    # Install Kustomize
    - name: Get Kustomize install script
      get_url:
        url: https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh
        dest: /tmp/install_kustomize.sh
        mode: +x
      register: result
      retries: 3
      until: result is success
    - name: Install Kustomize
      shell: /tmp/install_kustomize.sh && mv /tmp/kustomize  /usr/local/bin/kustomize && export PATH=$PATH:/usr/local/bin/kustomize
    - name: Confirm Kustomize is installed
      shell: kustomize version
      register: kustomize_result
      ignore_errors: yes
    - debug:
         var: kustomize_result

    # Install Sublime Text
    - name: Install GPG key for SubLime Text
      get_url:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        dest: /usr/share/keyrings/sublimehq-pub.gpg
        mode: '0644'
        force: true
      check_mode: no
    - name: Add specified repositories into sources list using specified filename
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/sublimehq-pub.gpg] https://download.sublimetext.com/ apt/stable/
        state: present
        filename: sublime
        update_cache: yes
      check_mode: no
    - name: Install SubLime Text
      apt:
        name: sublime-text
        update_cache: yes

    # Install Postman
    - name: Install Postman
      snap:
        name: postman
        classic: yes
    
    # Install Insomnia
    - name: Run Insomnia Setup Script
      shell: >
        curl -1sLf https://packages.konghq.com/public/insomnia/setup.deb.sh |
        sudo -E distro=ubuntu codename=focal bash
    - name: Install Insomnia
      apt:
        name: insomnia
        update_cache: yes

    # Install PuTTY SSH Client
    - name: Install PuTTY SSH Client
      apt:
        name: putty
        state: latest
        update_cache: yes
    
    # Install OpenVPN Client
    - name: Install OpenVPN Client
      apt:
        name: openvpn
        state: latest
        update_cache: yes

    # Install IntelliJ
    - name: Install IntelliJ IDEA Community
      snap:
        name: intellij-idea-community
        classic: yes

    # Install Microsoft Visual Studio Code
    - name: Add an apt signing key for Microsoft Visual Studio Code
      get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /usr/share/keyrings/microsoft.asc
        mode: '0644'
        force: true
      check_mode: no
    - name: Add apt repository for stable version of Visual Studio Code
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.asc] https://packages.microsoft.com/repos/vscode stable main
        state: present
        update_cache: yes
      check_mode: no
    - name: Install Microsoft Visual Studio Code
      apt:
        name: code
        state: present
        update_cache: yes
    - name: Confirm Microsoft Visual Studio Code is installed
      shell: code --version
      register: vscode_result
      ignore_errors: yes
      become: yes
      become_user: "{{ username }}"
    - debug:
         var: vscode_result

    # Install Microsoft Teams
    - name: Download Microsoft Teams deb package
      get_url:
        url: https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.4.00.7556_amd64.deb
        dest: /tmp/teams_1.4.00.7556_amd64.deb
      check_mode: no
      register: result
      retries: 3
      until: result is success
    - name: Install Microsoft Teams
      apt: deb=/tmp/teams_1.4.00.7556_amd64.deb
      ignore_errors: yes

    # Install pgAdmin4
    - name: Add an apt signing key for pgAdmin4
      get_url:
        url: https://www.pgadmin.org/static/packages_pgadmin_org.pub
        dest: /usr/share/keyrings/packages_pgadmin_org.pub
        mode: '0644'
        force: true
      check_mode: no
    - name: Add apt repository for pgAdmin4
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/packages_pgadmin_org.pub] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/{{ ansible_distribution_release }} pgadmin4 main"
        state: present
        update_cache: yes
      check_mode: no
    - name: Install pgAdmin4
      apt:
        name: pgadmin4
        state: latest
        update_cache: yes

    
    # Install MySQL Workbench
    - name: Add apt repository for MySQL Workbench
      apt_repository:
        repo: deb [trusted=yes arch=amd64] http://repo.mysql.com/apt/ubuntu {{ ansible_distribution_release }} mysql-tools
        state: present
        update_cache: yes
      check_mode: no
    - name: Install MySQL Workbench
      apt:
        name: mysql-workbench-community
        state: latest
        update_cache: yes
    
    # Install MongoDB
    - name: Add an apt signing key for mongoDB
      get_url:
        url: https://www.mongodb.org/static/pgp/server-6.0.asc
        dest: /usr/share/keyrings/server-6.0.asc
        mode: '0644'
        force: true
      check_mode: no
    - name: Add apt repository for mongoDB
      apt_repository:
        repo: deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/server-6.0.asc] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse
        state: present
        update_cache: yes
      check_mode: no
    - name: Install MongoDB
      apt:
        name: mongodb-mongosh
        update_cache: yes      
    - name: Confirm MongoDB is installed
      shell: mongod --version
      register: mongodb_result
      ignore_errors: yes
    - debug:
         var: mongodb_result

    # Install GIMP
    - name: Install GIMP
      apt:
        name: gimp
        state: latest
        update_cache: yes


    # Install ClamAV & ClamTK
    - name: Install ClamAV packages
      apt:
        name: "{{ clamav_packages }}"
        state: latest
        update_cache: yes
      vars:
        clamav_packages:
        - clamav
        - clamav-daemon
        - clamtk
    # - name: Stop the ClamAV service
    #   service:
    #     name: clamav-freshclam
    #     state: stopped
    # - name: Manually update the ClamAV signature database
    #   shell: freshclam
    # - name: Restart the ClamAV service
    #   service:
    #     name: clamav-freshclam
    #     state: restarted
    # - name: Download ClamTK deb package
    #   get_url:
    #     url: https://github.com/dave-theunsub/clamtk/releases/download/v6.14/clamtk_6.14-1_all.deb
    #     dest: /tmp/clamtk_6.14-1_all.deb
    #   check_mode: no
    #   register: result
    #   retries: 3
    #   until: result is success
    # - name: Install ClamTK
    #   apt: deb=/tmp/clamtk_6.14-1_all.deb

    # CLEANUP
    - name: Clean up tmp directory
      file:
        path: /tmp/*.deb
        state: absent
